name: hive_generator_io
description: Fork of the original hive_generator project. Updated to support latest versions of Dart and Flutter!
version: 3.0.1

environment:
  sdk: ^3.8.0

dependencies:
  analyzer: ^8.4.0
  build: ^4.0.2
  collection: ^1.19.1
  hive_io: ^3.0.0
  source_gen: ^4.0.2
  source_helper: ^1.3.8

dev_dependencies:
  build_runner: any
  build_test: any
  lint: ^2.8.0
  test: ^1.26.3
