name: hive_generator
description: Extension for Hive. Automatically generates TypeAdapters to store any class.
version: 1.3.0
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  analyzer: ^8.4.0
  build: ^4.0.2
  collection: ^1.19.1
  hive:
    path: ../hive
  source_gen: ^4.0.2
  source_helper: ^1.3.8

dev_dependencies:
  build_runner: any
  build_test: any
  lint: ^2.8.0
  test: ^1.26.3
