name: hive
description: Lightweight and blazing fast key-value database written in pure Dart. Strongly encrypted using AES-256.
version: 1.3.0
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  crypto: ^3.0.6
  meta: ^1.16.0

dev_dependencies:
  build_runner: ^2.10.1
  lint: ^2.8.0
  mocktail: ^1.0.4
  path: ^1.9.1
  pointycastle: ^4.0.0
  test: ^1.26.3
